[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional --no-package-lock"
  PRISMA_GENERATE_DATAPXY = "true"
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  SHARP_IGNORE_GLOBAL_LIBVIPS = "1"
  SHARP_DIST_BASE_URL = "https://npmmirror.com/mirrors/sharp-libvips/v0.32.6/"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", "sharp"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[dev]
  framework = "next"
  targetPort = 3000

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type" 