[build]
  command = "npm run build"
  publish = ".next/standalone"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"
  PRISMA_GENERATE_DATAPROXY = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 